### ISSUE TITLE
Game Crashes when I wanna see a recipe.

### ISSUE THREAD

**Issue by Leguan16** [Chicken-Bones/CodeChickenCore#104]
Hey!
Me and my friends created a little mod server (1.7.10 i think recommended forge version) with about 50 mods. 

When my friends joined we noticed that their game crashes when they wanna see a recipe. I can see every recipe but they do not. 
I gave a friend OP and it worked but on the next day it didn't

https://pastebin.com/mFGDDS3x

there is the crash report. I hope you can help me.

Noah

**Comment by MagmaSlime123** [comment]
NEI is dead.

**Comment by Leguan16** [comment]
but good.
