### ISSUE TITLE
Curious annotation in mod initialization

### ISSUE THREAD

**Issue by Wolfseverest93** [Chicken-Bones/CodeChickenCore#24]
as the title says, when i load up minecraft, my launcher shoots a creepy annotation about chickenlib, calling it dangerous and saying it could cause severe stability issues, a direct copy of that annotation: [23:57:42] [Client thread/INFO] [FML]: FML has found a non-mod file CodeChickenLib-1.7.10-1.1.1.99-universal.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.

is this normal, or should i put it into the 1.7.10 folder in the mod folder, where i put the other main libs and cores?

**Comment by Chicken-Bones** [comment]
It's fine, don't worry about that warning. mods or mods/1.7.10 makes no difference
