### ISSUE TITLE
ClassNotFoundException: net.minecraft.client.renderer.entity

### ISSUE THREAD

**Issue by HoldYourWaffle** [Chicken-Bones/CodeChickenCore#27]
When i use CCC (only CCC) in my eclipse forge setup, i get the following crash:
http://pastebin.com/VhfH638W

When CCC asked for the MCP, i selected the right folder with the fields.csv, methods.csv and joined.srg.

What must i do to let it work?

**Comment by Chicken-Bones** [comment]
It would appear your methods.csv doesn't match the name of that function in your workspace, can you confirm?

**Comment by Ravian2002** [comment]
I don't use any CCC functions in my mod/workspace, i want NEI in my workspace so i putted CCC inside the mods folder

**Comment by Chicken-Bones** [comment]
net/minecraft/client/renderer/entity/RenderItem.func_180454_a(Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/resources/model/IBakedModel;)V

Most likely that function has a different name in your workspace, than it does in the methods.csv you've linked, if that's the case, please find the right methods.csv, if that's not the case, then I'll have to look into it further

**Comment by Ravian2002** [comment]
This is my methods.csv:
http://pastebin.com/dnENQbE6
