### ISSUE TITLE
FluidStack.getFluidID()I issue

### ISSUE THREAD

**Issue by accessdenied0** [Chicken-Bones/CodeChickenCore#33]
Dear Chicken-Bones' Team,

I got recently an Ticking block entity in mid game as I tried to use a Translocator to transport Fluids from Tinkers Construct. The strange thing about: I did the same action just in another world and it works. Since then I changed NOTHING on Forge, CC or any other CC-mod. Why crashed it now?
It might be TConst. but I'm not sure. Here is the Log: http://pastebin.com/yQX6L3dc

I thank you for help,

access_denied

**Comment by Chicken-Bones** [comment]
Update Forge (sorry for taking a while to respond to this)

**Comment by accessdenied0** [comment]
Dear @Chicken-Bones ,

Sorry for my words but: This doesn't make any sense to me. Like I said: It works just fine with 1291. I changed NOTHING on the CC-mods and suddenly it uses from itself the API from 13XX+ ?

What?

access_denied

**Comment by Chicken-Bones** [comment]
Step 1. Have a liquid transposer moving fluid
Step 2. Crash
Step 3. Update Forge
Step 4. No crash

Some mod probably updated CodeChickenLib on you

**Comment by accessdenied0** [comment]
@Chicken-Bones ,

Is see. It isn't like I understand this steps, but... I was pretty sure no mod had updated the CC-Lib. Maybe I just got wrong, but I'm not retarded.

access_denied

**Comment by Chicken-Bones** [comment]
Don't worry, I apologise for any rudeness on my end, at least it's fixed hey
