### ISSUE TITLE
MCPDeobfuscationTransformer causes Forestry to crash in dev environment if GregTech is installed

### ISSUE THREAD

**Issue by bdew** [Chicken-Bones/CodeChickenCore#38]
Here's a log: https://www.dropbox.com/s/5a6ayt53k2z7rcr/deobfcrash.log?dl=0

I've spent a few good hours tracing the load process to figure out what's going on, and this is what i think is the order of events that lead to this crash:

* Gregtech jar contains 2 @Mod classes - GT_Api (modid gregapi) and GT_Mod (modid gregtech)
* gregapi has before:Forestry (and a bunch of other stuff)
* gregapi gets construction event
* forestry is not in class path yet 
* ProxyInjector is injecting @SidedProxy into both GT_Mod and GT_Api (It checks all annotations in the same container - jar file)
* GT_Mod.class is loaded
* MCPDeobfuscationTransformer (from CCC) runs on GT_Mod
* GT_Mod references forestry.factory.gadgets.MachineCentrifuge$RecipeManager and the transformer is trying to load it
* Forestry is not on class path yet, so it’s not found and is added to LaunchClassLoader.negativeResourceCache
* This doesn’t cause an error because MCPDeobfuscationTransformer ignores it (good)

[…. some time later  ….]

* Forestry is loading - it is now on class path

[…. some time later  ….]

* Forestry gets preInit event
* It attempts to access MachineCentrifuge$RecipeManager
* LaunchClassLoader sees it in negativeResourceCache and thinks that it’s not found
* crash!

I'm not sure how this could be fixed, either prevent MCPDeobfuscationTransformer from touching classes that can't be loaded yet or maybe somehow reset negativeResourceCache when it's done working?

**Comment by Chicken-Bones** [comment]
FMLModContainer.constructMod:437
modClassLoader.clearNegativeCacheFor(candidate.getClassList());

not functioning properly?

**Comment by bdew** [comment]
Hm i totally missed that. I'll check.

**Comment by bdew** [comment]
Oh yeah, looks like clearNegativeCacheFor is absolutely useless there. The negative cache uses a different format (forestry.factory.gadgets.MachineCentrifuge vs forestry/factory/gadgets/MachineCentrifuge) and moreover ModCandidate.foundClasses doesn't include inner classes anyway.

I'll open a bug against FML (or forge since they were merged?). Not sure if you want to add some kind of workaround for that, otherwise this can be closed.

**Comment by Chicken-Bones** [comment]
Suggestion for a fix on my end?

**Comment by bdew** [comment]
You could do something like this to clear the negative entries right away:

```
else
    Launch.classLoader.clearNegativeEntries(new HashSet<String>(Collections.singletonList(name)));
```

In [MCPDeobfuscationTransformer:206](https://github.com/Chicken-Bones/CodeChickenCore/blob/master/src/codechicken/core/asm/MCPDeobfuscationTransformer.java#L206) (and possibly in other places if there are similar calls, this is the one that was triggering the problem in my case)

I'm not sure if it's worth the hackiness (and possible performance cost) considering this is an edge case that only happens in dev environment. I can live with it being broken until hopefully fixed in FML.

**Comment by Chicken-Bones** [comment]
There you go 3307b52f09185610efc932df65e477cfeb7b9150 (1.7.10-1.0.6.44)
