### ISSUE TITLE
Unable to find mappings directory

### ISSUE THREAD

**Issue by The-Fireplace** [Chicken-Bones/CodeChickenCore#41]
In the dev environment, when trying to load the mod, a window pops up asking to select a directory, and, seeing as I don't know where to point it, just press select until the game crashes. Here is the log from the first time clicking select until the crash.
http://paste.ubuntu.com/11196457/
Can you either tell me where to point it or make it so I don't have to?

**Comment by Chicken-Bones** [comment]
You have to point it to a directory containing 3 files: methods.csv, fields.csv, and packaged.srg. Which contain the obfuscation mappings that you are using. You can probably find them in your .gradle folder

**Comment by The-Fireplace** [comment]
I have done a full computer search, the last time the csv files showed up in my workspaces was 1.6.4. The packaged.srg only showed up in 2 of my 8 1.8 workspaces. Do you have any idea how to generate them?

**Comment by Chicken-Bones** [comment]
Mine is in
C:\Users\cb\.gradle\caches\minecraft\net\minecraftforge\forge\1.7.10-10.13.3.1373-1.7.10\unpacked\conf

**Comment by The-Fireplace** [comment]
Ok, I will check there.

**Comment by The-Fireplace** [comment]
Ok, did that, new problem. It now crashes when I try to load the game. Here is the report.
paste.ubuntu.com/11270269/

**Comment by The-Fireplace** [comment]
I suppose the initial issue was solved, in a way. Creating a new issue for the, well, new issue.
