### ISSUE TITLE
CCC 1.0.7.45 Crash with Translocators 1.1.1.14

### ISSUE THREAD

**Issue by dirtyfargo** [Chicken-Bones/CodeChickenCore#46]
Crash on startup, with only CCC 1.0.7.45, Translocators 1.1.1.14, and NEI 1.0.5.110 installed.
Forge Version: 10.13.3.1408
Crash Report: http://pastebin.com/YKxUEHsi
Full FML Log: http://pastebin.com/JZac65Wf

**Comment by Dream-Master** [comment]
got the same crash

**Comment by Chicken-Bones** [comment]
Should be fixed in Translocator 1.1.2.15
CCC 1.0.7.46 will enforce this update
