### ISSUE TITLE
Crash Unsupported major.minor versi...

### ISSUE THREAD

**Issue by Vinny0thegamer** [Chicken-Bones/CodeChickenCore#51]
I have java 7u79 installed but I still get:

Unsupported major.minor version 51.0       <------The point zero does not matter

It should work because:
- J2SE 8 = 52
- **J2SE 7 = 51**
- J2SE 6.0 = 50
- J2SE 5.0 = 49
- JDK 1.4 = 48
- JDK 1.3 = 47
- JDK 1.2 = 46
- JDK 1.1 = 45

This feels like codechicken core because in the log you can see **"CoreModManager"**

Full log is here: http://pastebin.com/CnbL393J

Also I am on a mac

**Comment by Chicken-Bones** [comment]
mekanism/common/asm/LoadingHook 
Mekanism issue, probably means he compiled with Java 8 by accident
