### ISSUE TITLE
Weird Lighting Issue [1.8]

### ISSUE THREAD

**Issue by DatrixTHLK** [Chicken-Bones/CodeChickenCore#55]
Whenever I go into the inventory screen the blocks of dirt seem to light up. (For NEI 1.8 latest version)

**Comment by GirafiStudios** [comment]
I have already reported this.
Duplicate of https://github.com/Chicken-Bones/NotEnoughItems/issues/243

**Comment by DatrixTHLK** [comment]
I see thanks for reporting then
